version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  books:
    build: ./books
    restart: always
    volumes:
      - type: bind
        source: ./books
        target: /app
    ports:
      - "5001:80"
    environment:
       - MONGO_URL=mongodb://mongo:27017/BooksDB
       - PORT=80
    depends_on:
      - "mongo"

  loans:
    build: ./loans
    restart: always
    volumes:
      - type: bind
        source: ./loans
        target: /app
    ports:
      - "5002:80"
    environment:
      - MONGO_URL=mongodb://mongo:27017/LoansDB
    depends_on:
      - "mongo"
      - "books"

  loans-2:
    build: ./loans
    restart: always
    volumes:
      - type: bind
        source: ./loans
        target: /app
    environment:
      - MONGO_URL=mongodb://mongo:27017/LoansDB
    ports:
      - "5003:80"
    depends_on:
      - "mongo"
      - "books"

  nginx:
    image: nginx:latest # pulling image from DockerHub
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    depends_on:
      - "books"
      - "loans"
      - "loans-2"