version: '3.8'  # Using version 3.8 of the Docker Compose file format

services:
  nginx:
    image: nginx:latest # pulling image from DockerHub
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - books
      - loans

  books:
    build: ./books
    restart: always
    volumes:
      - type: bind
        source: ./books
        target: /books
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5001:80"
    depends_on:
      - mongo

  loans:
    build: ./loans
    restart: always
    volumes:
      - type: bind
        source: ./loans
        target: /loans
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5002:80"
    depends_on:
      - mongo
      - books

  loans-2:
    build: ./loans
    restart: always
    volumes:
      - type: bind
        source: ./loans
        target: /loans
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5003:80"
    depends_on:
      - mongo
      - books

  mongo:
    image: mongo
    ports:
      - "27017:27017"



